CREATE TABLE BILL(ID_BILL SERIAL PRIMARY KEY,
				  BILL_NAME VARCHAR(400) NOT NULL,
				   ORIGINAL_PRICE NUMERIC NOT NULL, 
				   DUE_DATE DATE NOT NULL, 
				   PAY_DATE DATE NOT NULL, 
				   INTEREST NUMERIC NOT NULL, 
				   FINE NUMERIC NOT NULL);